CREATE TABLE USERS (
	ID UUID DEFAULT GEN_RANDOM_UUID () PRIMARY KEY,
	FORENAME VARCHAR(100),
	SIRNAME VARCHAR(100),
	EMAIL VARCHAR(255) UNIQUE NOT NULL,
	HASH TEXT NOT NULL,
	CREATED TIMESTAMPTZ DEFAULT NOW(),
	UPDATED TIMESTAMPTZ DEFAULT NOW()
);