export { default as HeaderStyles } from './layout/Header.module.css';
export { default as MainStyles } from './layout/Main.module.css';
export { default as ViewStyles } from './layout/View.module.css';
export { default as ContainerStyles } from './layout/Container.module.css';
export { default as FooterStyles } from './layout/Footer.module.css';
export { default as NavStyles } from './layout/Nav.module.css';
export { default as PublicStyles } from './layout/Public.module.css';
export { default as PrivateStyles } from './layout/Private.module.css';
export { default as AsideStyles } from './layout/Aside.module.css';
