CREATE
OR REPLACE FUNCTION CLEANUP_EXPIRED_SESSIONS () RETURNS TRIGGER AS $$
BEGIN
    DELETE FROM SESSIONS WHERE EXPIRES <= NOW();
    RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

CREATE TRIGGER TRIGGER_CLEANUP_SESSIONS BEFORE INSERT ON SESSIONS FOR EACH ROW
EXECUTE FUNCTION CLEANUP_EXPIRED_SESSIONS ();