name: Pull Request
description: Use this template to create a pull request.
title: '[PR] '
labels: ''
assignees: ['sr-githaka']

body:
    - type: markdown
      attributes:
          value: |
              ## Description
              Please include a summary of the changes and the related issue.

    - type: textarea
      id: related-issue
      attributes:
          label: Related Issue
          description: Please link the issue this pull request addresses.
          placeholder: 'e.g., #123'
      validations:
          required: true

    - type: textarea
      id: changes
      attributes:
          label: Changes
          description: Describe the changes made in this pull request.
          placeholder: 'List of changes'
      validations:
          required: true

    - type: textarea
      id: testing
      attributes:
          label: Testing
          description: Describe how the changes were tested.
          placeholder: 'Testing instructions'
      validations:
          required: true

    - type: textarea
      id: checklist
      attributes:
          label: Checklist
          description: |
              - [ ] My code follows the style guidelines of this project
              - [ ] I have performed a self-review of my code
              - [ ] I have commented my code, particularly in hard-to-understand areas
              - [ ] I have made corresponding changes to the documentation
              - [ ] My changes generate no new warnings
              - [ ] I have added tests that prove my fix is effective or that my feature works
              - [ ] New and existing unit tests pass locally with my changes
      validations:
          required: true

    - type: textarea
      id: additional-context
      attributes:
          label: Additional Context
          description: Add any other context or screenshots about the pull request.
          placeholder: 'Additional context'
