name: Bug report
description: Create a report to help us improve
title: '[BUG] '
labels: bug
assignees: ''

body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this bug report! Please review the sections below and provide as much detail as possible.

    - type: input
      id: description
      attributes:
          label: Description
          description: A clear and concise description of what the bug is.
          placeholder: Provide a detailed description of the issue.
      validations:
          required: true

    - type: textarea
      id: steps-to-reproduce
      attributes:
          label: Steps to reproduce
          description: |
              Steps to reproduce the behavior:
              1. Go to '...'
              2. Click on '...'
              3. Scroll down to '...'
              4. See error
          placeholder: Provide detailed steps to reproduce the issue.
      validations:
          required: true

    - type: textarea
      id: expected-behavior
      attributes:
          label: Expected behavior
          description: A clear and concise description of what you expected to happen.
          placeholder: Describe what you expected to happen.
      validations:
          required: true

    - type: textarea
      id: actual-behavior
      attributes:
          label: Actual behavior
          description: A clear and concise description of what actually happened.
          placeholder: Describe what actually happened.
      validations:
          required: true

    - type: input
      id: environment
      attributes:
          label: Environment
          description: Run `pnpm next info` to get your system information.
          placeholder: Provide your system information.
      validations:
          required: true

    - type: textarea
      id: additional-context
      attributes:
          label: Additional context
          description: Add any other context about the problem here.
          placeholder: Provide any additional context.
